# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-18 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180818_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='allcoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='helicopdrones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heli', models.IntegerField()),
                ('drones', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='alllocations',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
